language: go

arch: amd64

os:
  - windows
  - linux
  - osx # default: MacOS 10.13, Kernel 17.6.0

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

go: 1.14.x

env:
  - GO111MODULE=off

install:
  - echo ""

before_script:
  - echo "Cloning"
  - mkdir golang
  - cd golang
  - git version
  - git clone --branch master --single-branch --no-tags https://github.com/golang/go.git
  - pwd
  - cd go
  - echo "On tip"
  - git log -1 --pretty=short
  - echo "Set up"
  - export GOROOT_BOOTSTRAP=$(go env GOROOT)
  - go env
  - echo "Merge travis ci fixes"
  - cd ../..
  - pwd
  - mv make_travisci.bash ./golang/go/src/make.bash
  - mv *.patch ./golang/go
  - cd golang/go
  - git apply -v --ignore-space-change --ignore-whitespace --whitespace=fix *.patch

script:
  - pwd
  - cd src
  - sh ./make.bash

after_success:
  - rm -f ./cmd/dist/dist
  - export GOROOT=
  - echo $GOROOT
  - cd ..
  - pwd
  - ./bin/go tool dist version
  - ./bin/go tool dist test
