language: go

arch: amd64

os:
  # - windows
  # - linux
  - osx

jobs:
  include:
    # - os: linux
    #  dist: bionic
    # - os: linux
    #  dist: xenial
    - os: osx # MacOS 10.15.5, Darwin 19.6.0
      osx_image: xcode12.2
    - os: osx # MacOS 10.14.6, Darwin 18.7.0
      osx_image: xcode11.3
    - os: osx # MacOS 10.13, Darwin 17.7.0 for all images, fails when UTIME_OMIT is not both values
      osx_image: xcode10.1
    - os: osx # MacOS 10.12, Darwin 16.7.0, build fails on _utimensat
      osx_image: xcode9.2

go: 1.11.x

env:
  - GO111MODULE=off

install:
  - echo ""

before_script:
  - echo "syscall values"
  - gcc -E sys/syscall.h
  - echo "Cloning"
  - mkdir golang
  - cd golang
  - git version
  - git clone --branch master --single-branch --no-tags https://github.com/golang/go.git
  - pwd
  - cd go
  - echo "On tip"
  - git log -1 --pretty=short
  - echo "Set up"
  - export GOROOT_BOOTSTRAP=$(go env GOROOT)
  - go env
  - echo "Merge travis ci fixes"
  - cd ../..
  - pwd
  - mv make_travisci.bash ./golang/go/src/make.bash
  - mv *.patch ./golang/go
  - cd golang/go
  - git apply -v --ignore-space-change --ignore-whitespace --whitespace=fix *.patch

script:
  - pwd
  - cd src
  - sh ./make.bash

after_success:
  - rm -f ./cmd/dist/dist
  - export GOROOT=
  - echo $GOROOT
  - cd ..
  - pwd
  - ./bin/go tool dist version
  # - ./bin/go tool dist test
  - ./bin/go tool dist test -run=".*os"
