name: image test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      if: true
      with:
        go-version: 1.22.x
      id: go

    - uses: actions/checkout@v4
    - name: Enable KVM group perms
      if: false
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - uses: iwdgo/gotip-build@master
      id: gotip
      if: false
      with:
        go_variables: GOOS=freebsd
        test_build: 'false'
    - name: Test in FreeBSD
      run: |
        sudo apt install qemu-system-x86 virt-manager
        # sudo chmod u+rwx libvirt-qemu ./
        # Download freebsd
        freebsdrel=FreeBSD-14.2-RELEASE-amd64.qcow2.xz
        wget https://download.freebsd.org/ftp/releases/VM-IMAGES/14.2-RELEASE/amd64/Latest/FreeBSD-14.2-RELEASE-amd64.qcow2.xz
        xz --decompress $freebsdrel
        virsh pool-list
        ls -l /var/lib/libvirt/
        sudo mv FreeBSD-14.0-RELEASE-amd64.qcow2 /var/lib/libvirt/images/
        # Provision the image
        qemu-img resize /var/lib/libvirt/images/FreeBSD-14.0-RELEASE-amd64.qcow2 +2G
        # ps -ef | grep qemu-system-x86_64
        # Start
        # qemu-img resize FreeBSD-14.0-RELEASE-amd64.qcow2 +2G
        # sudo systemctl enable serial-getty@ttyS0.service
        # virt-install --osinfo list
        uname -a
        # sudo sshd -T
        # sudo ssh -G localhost
        # qemu-system-x86_64 -m 2048 \
        #   -hda FreeBSD-14.0-RELEASE-amd64.qcow2 -enable-kvm \
        #   -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22 \
        #   -device e1000,netdev=mynet0 \
        #   -nographic \
        #   -serial unix:console.sock,server,nowait \
        #   console=ttyS0,38400n8 earlyprint=serial,ttyS0,38400n8 \
        #   freebsd.qcow2 +1G
        # Trying defaults
        # qemu-img create -f qcow2 -o preallocation=off FreeBSD-14.0-RELEASE-amd64.qcow2 +2G
        # bus=...:virtio ?
        sudo virt-install --connect qemu:///system \
          --name freebsd140 \
          --memory 2048 \
          --osinfo freebsd14.0 \
          --network network=default,model=e1000,model=virtio \
          --nographics \
          --virt-typ qemu \
          --disk /var/lib/libvirt/images/FreeBSD-14.0-RELEASE-amd64.qcow2,bus=virtio \
          --import
        # virsh start freebsd140
        # virsh list --all
        # qemu-system-x86_64 -drive file=FreeBSD-14.0-RELEASE-amd64.qcow2,format=qcow2 -nographic \
        #  freebsd +1G
        # socat STDIO,cfmakeraw UNIX:console.sock
        # Enter Freebsd
        # ssh -p 7722 root@localhost
        uname -a
        # pkg install -y socat # freebsd package
        # sysrc sshd_enable="YES" ifconfig_em0="DHCP"
        # sed -i '$a PermitRootLogin prohibit-password" /etc/ssh/sshd.conf
        # service netif restart
        # service sshd start
        ls -la
        pwd
