name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
        architecture: x86
      id: go

    - name: Check environment
      run: |
        git version

    - name: Clone go on tip
      run: |
        git clone https://github.com/golang/go.git --branch master --single-branch --no-tags
        cd go/src
        git log -1 --pretty=short

    - name: Toolstash save
      run: |
        go get -u golang.org/x/tools/...
        toolstash || true
        toolstash -v save || true

    - name: Merge patch
      run: |
        mv *.patch go
        cd go
        git apply -v --ignore-space-change --ignore-whitespace --whitespace=fix *.patch

    - name: Run compiler rules
      run: |
        cd go/src/cmd/compile/internal/ssa/gen
        go run *.go

    - name: Build
      run: |
        cd go/src
        export GOROOT_BOOTSTRAP=$(go env GOROOT)
        sh ./make.bash

    - name: Test
      run: |
        cd go/bin
        export GOROOT=
        go tool dist version
        go tool dist test

    - name: Toolstash -cmp
      run: |
        cd go/bin
        export GOROOT=
        go tool dist install cmd/compile
        go build -toolexec 'toolstash -cmp' -a std
