name: linux
on:
  push:
    branches:
      - 'issue'
    paths:
      - '.github/workflows/linux.yml'

jobs:

  build:
    strategy:
      matrix:
        go_arch: [amd64]
      fail-fast: false
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
      id: go

    - name: Access file system
      uses: actions/checkout@v4

    - name: Format patches
      run: |
        # Create patches and apply
        # go.dev/issue/24233
        git fetch https://go.googlesource.com/go refs/changes/75/669775/2 && git checkout -b change-669775 FETCH_HEAD && git format-patch -1

    - name: Build go from tip
      uses: iwdgo/gotip-build@master
      id: gotip
      with:
        go_variables: GO_TEST_SHORT=0 GO_TEST_TIMEOUT_SCALE=5
        test_build: 'true'

    - name: Run 'go test golang.org/x/tools module'
      run: |
        go/bin/go version
        go/bin/go env
        git clone --depth=1 --branch master --single-branch --no-tags https://github.com/golang/tools.git
        cd tools/
        ../go/bin/go test ./...
